-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 11:51:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema checkpoint4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `checkpoint4` ;

-- -----------------------------------------------------
-- Schema checkpoint4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint4` DEFAULT CHARACTER SET utf8 ;
USE `checkpoint4` ;

-- -----------------------------------------------------
-- Table `checkpoint4`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`company` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `localisation` VARCHAR(255) NULL,
  `activity` VARCHAR(255) NOT NULL,
  `imgCompany` VARCHAR(45) NULL,
  `sinceCompany` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checkpoint4`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`product` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nameProduct` VARCHAR(255) NOT NULL,
  `sinceProduct` VARCHAR(45) NULL,
  `imgProduct` VARCHAR(255) NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_product_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `checkpoint4`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checkpoint4`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`category` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(255) NOT NULL,
  `product_id` INT NOT NULL,
  `product_company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`, `product_company_id`),
  INDEX `fk_category_product1_idx` (`product_id` ASC, `product_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_product1`
    FOREIGN KEY (`product_id` , `product_company_id`)
    REFERENCES `checkpoint4`.`product` (`id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checkpoint4`.`category_has_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint4`.`category_has_company` ;

CREATE TABLE IF NOT EXISTS `checkpoint4`.`category_has_company` (
  `category_id` INT NOT NULL,
  `category_product_id` INT NOT NULL,
  `category_product_company_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `category_product_id`, `category_product_company_id`, `company_id`),
  INDEX `fk_category_has_company_company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_category_has_company_category1_idx` (`category_id` ASC, `category_product_id` ASC, `category_product_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_company_category1`
    FOREIGN KEY (`category_id` , `category_product_id` , `category_product_company_id`)
    REFERENCES `checkpoint4`.`category` (`id` , `product_id` , `product_company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_company_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `checkpoint4`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
